---
apiVersion: v1
kind: Service
metadata:
  name: tutorial
spec:
  ports:
      - name: 80-tcp
        port: 80
        protocol: TCP
        targetPort: 80
  selector:
    com.docker.project: tutorial
  type: LoadBalancer
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: tutorial
  name: guid-service-1
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: tutorial
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: tutorial
    spec:
      containers:
        - image: acrazcourse.azurecr.io/guid-service:v1
          name: tutorial
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: InstanceId
              value: local-kube-1
            - name: TableSettings__ConnectionString
              value: ""
          resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.docker.project: tutorial
  name: guid-service-2
spec:
  replicas: 1
  selector:
    matchLabels:
      com.docker.project: tutorial
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        com.docker.project: tutorial
    spec:
      containers:
        - image: acrazcourse.azurecr.io/guid-service:v1
          name: tutorial
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: InstanceId
              value: local-kube-2
            - name: TableSettings__ConnectionString
              value: ""
          resources: {}
      restartPolicy: Always
status: {}